version: "3.7"
services:
  website:
    image: node:10
    command: npm run dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
